services:
  postgres:
    image: postgres:15-alpine
    container_name: zenix-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: zenix_db
    volumes: 
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


# Untuk running docker (melanjutkan developmet)
# docker-compose start
# atau bisa dengan
# docker-compose up -d

# Untuk jeda singkat docker container dan menghentikan container yang berjalan
# docker-compose stop